version: '3'
services:

  api:
    build: api/.
    ports:
      - "8080:8080"    
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - net-backend  
  mysql:
    container_name: mysql
    build: mysql/.
    ports:
      - "3306:3306"
    hostname: mysql
    volumes:
      - /var/lib/mysql    
    environment:
      MYSQL_DATABASE: 'notes_app'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root' 
    networks:
      - net-backend   
    expose:
      - "3306"
networks:
  net-backend:
    driver: bridge