version: '3'
services:

  api:
    image: dayserivera/arquiteturademicrocontainers_mysql
    restart: on-failure
    ports:
      - "8080:8080"    
    depends_on:
      - mysql    
    networks:
      - net-backend  
  mysql:
    image: dayserivera/arquiteturademicrocontainers_mysql
    container_name: mysql    
    ports:
      - "3306:3306"
    hostname: mysql
    volumes:
      - /var/lib/mysql    
    environment:
      MYSQL_DATABASE: notes_app            
      MYSQL_ROOT_PASSWORD: root
    networks:
      - net-backend   
    expose:
      - "3306"
networks:
  net-backend:
    driver: bridge